baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[services]
  [services.googleAnalytics]
    ID = "G-XXXXXXXXXX"  # Your GA4 measurement ID

[params]
  CoverImage = '/images/cover_image.png'
  
  # Timeline Starting Point (optional)
  # timelineStart = "ðŸš€ And so it begins..."
  # timelineStartSubText = "Additional context or details..."
  # timelineStartDate = "Jan 2023"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
